name: Test Public

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    # Checkout main repo
    - name: Checkout main repository
      uses: actions/checkout@v4

    - name: script
      run: |
        git rev-parse HEAD
        ls
        git remote -v
        echo "public"

  build2:
    runs-on: ubuntu-22.04

    steps:
    # Checkout main repo
    - name: Checkout main repository
      uses: actions/checkout@v4

    - name: script
      run: |
        git rev-parse HEAD
        ls
        git remote -v
        echo "public"
        find .



