name: Test Private

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.private }}  # This job runs only if the repository is private

    steps:
    # Checkout main repo
    - name: Checkout main repository
      uses: actions/checkout@v4

    - name: script
      run: |
        git rev-parse HEAD
        ls
        git remote -v

  build2:
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.private }}  # This job runs only if the repository is private

    steps:
    # Checkout main repo
    - name: Checkout main repository
      uses: actions/checkout@v4

    - name: script
      run: |
        git rev-parse HEAD
        ls
        git remote -v
        find .



